import { Geist, Geist_Mono } from 'next/font/google';
import { Navbar, Footer } from './components';
import './globals.css';
import Head from 'next/head';

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
});

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
});

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <Head></Head>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased  mx-auto `}
      >
        <div className="container max-w-[1800px] mx-auto">
          <Navbar />
          {children}
        </div>
        <Footer />
      </body>
    </html>
  );
}
